import { LibraryAsset, Track } from "./types";

export const DEFAULT_ASSETS: LibraryAsset[] = [
  // Stock Videos (Procedurally simulated inside Canvas with beautiful styling patterns)
  {
    id: "vid_cyber",
    name: "Cyberpunk Neon Drive",
    type: "video",
    category: "Tech & Cyber",
    mediaUrl: "cyber-neon-drive",
    thumbnailUrl: "🌆",
    duration: 10,
    colorScheme: "cyberpunk",
  },
  {
    id: "vid_ocean",
    name: "Calm Beach Ocean Waves",
    type: "video",
    category: "Nature & Chill",
    mediaUrl: "calm-beach-waves",
    thumbnailUrl: "🌊",
    duration: 8,
    colorScheme: "oceanic",
  },
  {
    id: "vid_workout",
    name: "High-Intensity Fitness",
    type: "video",
    category: "Gym & Sports",
    mediaUrl: "intense-power-gym",
    thumbnailUrl: "🏋️",
    duration: 6,
    colorScheme: "energy",
  },
  {
    id: "vid_coffee",
    name: "Morning Brewing Espresso",
    type: "video",
    category: "Vlog & Lifestyle",
    mediaUrl: "morning-espresso",
    thumbnailUrl: "☕",
    duration: 7,
    colorScheme: "lofi",
  },
  {
    id: "vid_sunset",
    name: "Scenic Golden Hour Sunset",
    type: "video",
    category: "Travel & Scenic",
    mediaUrl: "gold-sunset-scenic",
    thumbnailUrl: "🌅",
    duration: 9,
    colorScheme: "sunset",
  },
  {
    id: "vid_greenscreen_dino",
    name: "AURA Tyrannosaurus (Green Screen)",
    type: "video",
    category: "Chroma & Overlays",
    mediaUrl: "aura-greenscreen-dino",
    thumbnailUrl: "🦖",
    duration: 8,
    colorScheme: "chromakey",
  },
  {
    id: "vid_greenscreen_robot",
    name: "AURA Dancing Bot (Green Screen)",
    type: "video",
    category: "Chroma & Overlays",
    mediaUrl: "aura-greenscreen-robot",
    thumbnailUrl: "🤖",
    duration: 10,
    colorScheme: "chromakey",
  },

  // Audio Music Soundtracks
  {
    id: "aud_synthwave",
    name: "Midnight Outrun Synthwave",
    type: "audio",
    category: "Beats & Music",
    mediaUrl: "synthwave-sunset-chase",
    thumbnailUrl: "🎵",
    duration: 30,
  },
  {
    id: "aud_lofi",
    name: "Warm Cafe Soft Lofi Calm",
    type: "audio",
    category: "Beats & Music",
    mediaUrl: "warm-cafe-soft-lofi",
    thumbnailUrl: "🎧",
    duration: 30,
  },
  {
    id: "aud_heroic",
    name: "Rise of Heroes Orchestral",
    type: "audio",
    category: "Beats & Music",
    mediaUrl: "epic-heroic-orchestra",
    thumbnailUrl: "🎻",
    duration: 30,
  },

  // Audio SFX Sound Effects
  {
    id: "sfx_swoosh",
    name: "Dynamic Whoosh Swoosh",
    type: "audio",
    category: "Sound Effects",
    mediaUrl: "whoosh-swift",
    thumbnailUrl: "💨",
    duration: 2,
  },
  {
    id: "sfx_glitch",
    name: "Sci-Fi Digital Glitch",
    type: "audio",
    category: "Sound Effects",
    mediaUrl: "digital-glitch-buzz",
    thumbnailUrl: "👾",
    duration: 1.5,
  },
  {
    id: "sfx_shutter",
    name: "DSLR Camera Shutter Snapshot",
    type: "audio",
    category: "Sound Effects",
    mediaUrl: "camera-shutter-snap",
    thumbnailUrl: "📸",
    duration: 1,
  },

  // Emojis / Sticker Overlays
  {
    id: "stk_fire",
    name: "🔥 Fire Blast Sparkle",
    type: "text",
    category: "Stickers",
    mediaUrl: "🔥",
    thumbnailUrl: "🔥",
    duration: 4,
  },
  {
    id: "stk_heart",
    name: "💖 Sparkling Radiant Heart",
    type: "text",
    category: "Stickers",
    mediaUrl: "💖",
    thumbnailUrl: "💖",
    duration: 4,
  },
  {
    id: "stk_glasses",
    name: "😎 Cool Thug Sunglasses",
    type: "text",
    category: "Stickers",
    mediaUrl: "😎",
    thumbnailUrl: "😎",
    duration: 5,
  },
  {
    id: "stk_trophy",
    name: "🏆 Golden Champion Trophy",
    type: "text",
    category: "Stickers",
    mediaUrl: "🏆",
    thumbnailUrl: "🏆",
    duration: 5,
  },
];

export const TRANSITION_TYPES = [
  { id: "none", name: "None - Hard Cut" },
  { id: "fade", name: "Cross Fade" },
  { id: "dissolve", name: "Ripple Dissolve" },
  { id: "slide-left", name: "Slide Left" },
  { id: "slide-right", name: "Slide Right" },
  { id: "wave", name: "Dynamic Spin Wave" },
  { id: "zoom", name: "Camera Zoom Zoom" },
];

export const FILTER_PRESETS = [
  { id: "None", name: "None (Raw Footage)" },
  { id: "Cinema Teal", name: "🎬 Cinematic Teal & Orange" },
  { id: "Cyber Glitch", name: "🌌 Cyber Hologram Glitch" },
  { id: "Retro VHS", name: "📼 Retro VHS Tape" },
  { id: "Noir", name: "🕶️ Classic Black & White Noir" },
  { id: "Vintage gold", name: "🎞️ Golden Vintage Sepia" },
  { id: "Chrome Acid", name: "🔋 Chrome Acid Neon" },
];

export const TEXT_STYLES = [
  {
    id: "neon_gradient",
    name: "Neon Glow Impact",
    fontFamily: "Space Grotesk",
    fontColor: "#FF1493",
    fontSize: 24,
    fontBgColor: "rgba(0, 0, 0, 0.75)",
    textAnimation: "bounce",
  },
  {
    id: "vintage_serif",
    name: "Vintage Cinematic Gold",
    fontFamily: "Playfair Display",
    fontColor: "#F39C12",
    fontSize: 28,
    fontBgColor: "transparent",
    textAnimation: "fade",
  },
  {
    id: "hacker_mono",
    name: "Hacker Terminal Monospace",
    fontFamily: "JetBrains Mono",
    fontColor: "#00FF00",
    fontSize: 20,
    fontBgColor: "#000000",
    textAnimation: "typewriter",
  },
  {
    id: "bold_header",
    name: "Sleek Professional White",
    fontFamily: "Inter",
    fontColor: "#FFFFFF",
    fontSize: 22,
    fontBgColor: "rgba(30, 41, 59, 0.8)",
    textAnimation: "scale",
  },
];

export const KEYBOARD_SHORTCUTS = [
  { keys: "Space", action: "Play / Pause playback toggle" },
  { keys: "S", action: "Split highlight clip at current playhead" },
  { keys: "Backspace / Delete", action: "Delete highlighted item from tracks" },
  { keys: "Arrow Left", action: "Nudge playhead forward 1 frame" },
  { keys: "Arrow Right", action: "Nudge playhead backward 1 frame" },
  { keys: "Ctrl + C", action: "Copy highlighted clip" },
  { keys: "Ctrl + V", action: "Paste clip at playhead" },
  { keys: "M", action: "Quick mute / unmute highlighted clip" },
];

// Helper to provide nice seed timeline state so first-time boot looks packed and active
export const INITIAL_TIMELINE_TRACKS: Track[] = [
  {
    id: "track_video_main",
    name: "Video Layer 1",
    type: "video",
    isLocked: false,
    isMuted: false,
    clips: [
      {
        id: "clip_v1",
        name: "Cyberpunk Neon Drive",
        type: "video",
        startOffset: 0,
        duration: 6,
        mediaUrl: "cyber-neon-drive",
        thumbnailUrl: "🌆",
        properties: {
          volume: 80,
          speed: 1.0,
          scale: 100,
          posX: 0,
          posY: 0,
          filterName: "Cyber Glitch",
          brightness: 110,
          contrast: 120,
          saturation: 130,
          blur: 0,
          vignette: 15,
          opacity: 100,
          transitionType: "fade",
          transitionDuration: 1.0,
        },
      },
      {
        id: "clip_v2",
        name: "Morning Espresso Loop",
        type: "video",
        startOffset: 6,
        duration: 5,
        mediaUrl: "morning-espresso",
        thumbnailUrl: "☕",
        properties: {
          volume: 0,
          speed: 1.2,
          scale: 100,
          posX: 0,
          posY: 0,
          filterName: "Vintage gold",
          brightness: 100,
          contrast: 100,
          saturation: 110,
          blur: 0,
          vignette: 5,
          opacity: 100,
          transitionType: "zoom",
          transitionDuration: 0.8,
        },
      },
      {
        id: "clip_v3",
        name: "Scenic Golden Hour Sunset",
        type: "video",
        startOffset: 11,
        duration: 4,
        mediaUrl: "gold-sunset-scenic",
        thumbnailUrl: "🌅",
        properties: {
          volume: 100,
          speed: 0.8,
          scale: 110,
          posX: 0,
          posY: 0,
          filterName: "Cinema Teal",
          brightness: 95,
          contrast: 105,
          saturation: 125,
          blur: 0,
          vignette: 25,
          opacity: 100,
          transitionType: "dissolve",
          transitionDuration: 1.2,
        },
      },
    ],
  },
  {
    id: "track_text_captions",
    name: "Subtitles & Text",
    type: "text",
    clips: [
      {
        id: "clip_t1",
        name: "[SUB] Welcome to Vision",
        type: "text",
        startOffset: 0.5,
        duration: 3,
        mediaUrl: "",
        thumbnailUrl: "💬",
        properties: {
          volume: 0,
          speed: 1.0,
          scale: 100,
          posX: 0,
          posY: 100, // Move lower for subtitles
          filterName: "None",
          brightness: 100,
          contrast: 100,
          saturation: 100,
          blur: 0,
          vignette: 0,
          opacity: 100,
          textString: "WELCOME TO THE FUTURE",
          fontSize: 22,
          fontFamily: "Space Grotesk",
          fontColor: "#00FFFF",
          fontBgColor: "rgba(0,0,0,0.6)",
          textAlignment: "center",
          textAnimation: "bounce",
        },
      },
      {
        id: "clip_t2",
        name: "[SUB] Fuel with Espresso",
        type: "text",
        startOffset: 6.5,
        duration: 3.5,
        mediaUrl: "",
        thumbnailUrl: "💬",
        properties: {
          volume: 0,
          speed: 1.0,
          scale: 100,
          posX: 0,
          posY: 100,
          filterName: "None",
          brightness: 100,
          contrast: 100,
          saturation: 100,
          blur: 0,
          vignette: 0,
          opacity: 100,
          textString: "FUELING THE MIND: ESPRESSO SHOTS",
          fontSize: 20,
          fontFamily: "JetBrains Mono",
          fontColor: "#F1C40F",
          fontBgColor: "rgba(20,20,20,0.85)",
          textAlignment: "center",
          textAnimation: "typewriter",
        },
      },
    ],
  },
  {
    id: "track_audio_bg",
    name: "Music Soundtracks",
    type: "audio",
    isMuted: false,
    clips: [
      {
        id: "clip_a1",
        name: "Warm Cafe Soft Lofi",
        type: "audio",
        startOffset: 0,
        duration: 15,
        mediaUrl: "warm-cafe-soft-lofi",
        thumbnailUrl: "🎵",
        properties: {
          volume: 60,
          speed: 1.0,
          scale: 100,
          posX: 0,
          posY: 0,
          filterName: "None",
          brightness: 100,
          contrast: 100,
          saturation: 100,
          blur: 0,
          vignette: 0,
          opacity: 100,
        },
      },
    ],
  },
  {
    id: "track_sfx_trans",
    name: "Transition Effects",
    type: "audio",
    clips: [
      {
        id: "clip_sfx1",
        name: "Science Glitch Buzz",
        type: "audio",
        startOffset: 5.5,
        duration: 1.5,
        mediaUrl: "digital-glitch-buzz",
        thumbnailUrl: "⚡",
        properties: {
          volume: 90,
          speed: 1.0,
          scale: 100,
          posX: 0,
          posY: 0,
          filterName: "None",
          brightness: 100,
          contrast: 100,
          saturation: 100,
          blur: 0,
          vignette: 0,
          opacity: 100,
        },
      },
    ],
  },
];
